# build and test image on its own

version: '2'

services:
    db_node_one:
        build: .
        image: opendicom/mariadb-for-dcm4chee:10.1.14
        container_name: db_node_one
        command: ["mysqld", "--wsrep-new-cluster"]
        environment:
            MYSQL_ROOT_PASSWORD: secure
            MYSQL_DATABASE: awesome
            WSREP_ON: 'on'  # set to null to disable
            WSREP_CLUSTER_NAME: test-cluster
            WSREP_CLUSTER_ADDRESS: gcomm://db_node_one,db_node_two
            WSREP_NODE_NAME: db_node_one
            WSREP_NODE_ADDRESS: db_node_one
            REPLICATION_USER: replication
            REPLICATION_PASSWORD: password

    db_node_two:
        build: .
        image: opendicom/mariadb-for-dcm4chee:10.1.14
        container_name: db_node_two
        depends_on:
            - db_node_one
        environment:
            MYSQL_ROOT_PASSWORD: secure
            MYSQL_DATABASE: awesome
            WSREP_ON: 'on'  # set to null to disable
            WSREP_CLUSTER_NAME: test-cluster
            WSREP_CLUSTER_ADDRESS: gcomm://db_node_one,db_node_two
            WSREP_NODE_NAME: db_node_two
            WSREP_NODE_ADDRESS: db_node_two
            REPLICATION_USER: replication
            REPLICATION_PASSWORD: password
